

-- Query #1
SELECT o.ORDNO, USRNAME, TESTCODE, TESTNAME FROM orders AS o
JOIN ordtask AS ot ON o.ORDNO = ot.ORDNO ORDER BY TESTCODE; 

-- Query #2
SELECT o.ORDNO FROM orders AS o
JOIN ordtask AS ot ON o.ORDNO = ot.ORDNO WHERE TESTCODE = 123 ORDER BY TESTCODE;

-- Query #3
SELECT USRNAME FROM orders AS o
JOIN ordtask AS ot ON o.ORDNO = ot.ORDNO WHERE LEFT(TESTNAME, 11) = 'Измерения р' ORDER BY TESTCODE;